name = "appbakehouse theme"
license = "MIT"
description = "A theme used in appbakehouse"
tags = []
features = []
min_version = "0.0.0.0"

[author]
  name = "Chajin Oh"
  homepage = "http://www.appbakehouse.com"
